version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "admin4-products"

phases:
  install:
    runtime-versions:
      java: openjdk8
      
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $IMAGE_REPO_NAME
      - echo $AWS_ACCOUNT_ID
      - echo $AWS_DEFAULT_REGION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo start command
#      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn package -Dmaven.test.skip=true

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...

#cache:
#  paths:
#    - '/root/.m2/**/*'
